# Generated by Django 4.1.2 on 2023-01-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_11', models.CharField(default='', max_length=1)),
                ('p_12', models.CharField(default='', max_length=1)),
                ('p_13', models.CharField(default='', max_length=1)),
                ('p_21', models.CharField(default='', max_length=1)),
                ('p_22', models.CharField(default='', max_length=1)),
                ('p_23', models.CharField(default='', max_length=1)),
                ('p_31', models.CharField(default='', max_length=1)),
                ('p_32', models.CharField(default='', max_length=1)),
                ('p_33', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=6)),
                ('game_creator', models.CharField(max_length=50)),
                ('game_opponent', models.CharField(max_length=50)),
                ('game_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamematrix')),
            ],
        ),
    ]
