# Generated by Django 4.1.2 on 2023-01-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_opponent',
            field=models.CharField(default='to-be-decided', max_length=50),
        ),
    ]
