# Generated by Django 4.1.2 on 2023-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamematrix_p_11_alter_gamematrix_p_12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_11',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_12',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_13',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_21',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_22',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_23',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_31',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_32',
        ),
        migrations.RemoveField(
            model_name='gamematrix',
            name='p_33',
        ),
        migrations.AddField(
            model_name='gamematrix',
            name='matrix_map',
            field=models.CharField(default='[[11,12,13],[21,22,23],[31,32,33]]', max_length=50),
        ),
    ]
