# Generated by Django 4.1.2 on 2023-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_gamematrix_matrix_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematrix',
            name='matrix_map',
            field=models.CharField(default="['1','2','3','4','5','6','7','8','9']", max_length=50),
        ),
    ]
