# Generated by Django 4.2 on 2025-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gamematrix_matrix_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematrix',
            name='matrix_map',
            field=models.CharField(default='[1,2,3,4,5,6,7,8,9]', max_length=50),
        ),
    ]
